# Generated by Django 4.0.5 on 2022-07-05 09:46

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("yearborn", models.IntegerField(default=1900)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "competition_name",
                    models.CharField(blank=True, max_length=128),
                ),
                ("location", models.CharField(blank=True, max_length=128)),
                ("date_start", models.DateField(blank=True)),
                ("date_end", models.DateField(blank=True)),
            ],
            options={
                "ordering": ["-date_start", "competition_name"],
            },
        ),
        migrations.CreateModel(
            name="Lift",
            fields=[
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_number", models.IntegerField(null=True)),
                ("lottery_number", models.IntegerField(blank=True)),
                (
                    "bodyweight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "weight_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W45", "W45"),
                            ("W49", "W49"),
                            ("W55", "W55"),
                            ("W59", "W59"),
                            ("W64", "W64"),
                            ("W71", "W71"),
                            ("W76", "W76"),
                            ("W81", "W81"),
                            ("W87", "W87"),
                            ("W81+", "W81+"),
                            ("W87+", "W87+"),
                            ("M55", "M55"),
                            ("M61", "M61"),
                            ("M67", "M67"),
                            ("M73", "M73"),
                            ("M81", "M81"),
                            ("M89", "M89"),
                            ("M96", "M96"),
                            ("M102", "M102"),
                            ("M109", "M109"),
                            ("M102+", "M102+"),
                            ("M109+", "M109+"),
                            ("W48", "W48"),
                            ("W53", "W53"),
                            ("W58", "W58"),
                            ("W63", "W63"),
                            ("W69", "W69"),
                            ("W75", "W75"),
                            ("W90", "W90"),
                            ("W90+", "W90+"),
                            ("M56", "M56"),
                            ("M62", "M62"),
                            ("M69", "M69"),
                            ("M77", "M77"),
                            ("M85", "M85"),
                            ("M94", "M94"),
                            ("M105", "M105"),
                            ("M105+", "M105+"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "team",
                    models.CharField(blank=True, default="IND", max_length=20),
                ),
                (
                    "snatch_first",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIFT", "Good Lift"),
                            ("NOLIFT", "No Lift"),
                            ("DNA", "Did not attempt"),
                        ],
                        default="DNA",
                        max_length=6,
                    ),
                ),
                (
                    "snatch_first_weight",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "snatch_second",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIFT", "Good Lift"),
                            ("NOLIFT", "No Lift"),
                            ("DNA", "Did not attempt"),
                        ],
                        default="DNA",
                        max_length=6,
                    ),
                ),
                (
                    "snatch_second_weight",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "snatch_third",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIFT", "Good Lift"),
                            ("NOLIFT", "No Lift"),
                            ("DNA", "Did not attempt"),
                        ],
                        default="DNA",
                        max_length=6,
                    ),
                ),
                (
                    "snatch_third_weight",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "cnj_first",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIFT", "Good Lift"),
                            ("NOLIFT", "No Lift"),
                            ("DNA", "Did not attempt"),
                        ],
                        default="DNA",
                        max_length=6,
                    ),
                ),
                (
                    "cnj_first_weight",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "cnj_second",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIFT", "Good Lift"),
                            ("NOLIFT", "No Lift"),
                            ("DNA", "Did not attempt"),
                        ],
                        default="DNA",
                        max_length=6,
                    ),
                ),
                (
                    "cnj_second_weight",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "cnj_third",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIFT", "Good Lift"),
                            ("NOLIFT", "No Lift"),
                            ("DNA", "Did not attempt"),
                        ],
                        default="DNA",
                        max_length=6,
                    ),
                ),
                (
                    "cnj_third_weight",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.athlete",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["weight_category", "lottery_number"],
            },
        ),
    ]
