# Generated by Django 4.0.5 on 2022-07-12 11:30

import api.models.athletes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='yearborn',
            field=models.IntegerField(default=1900, validators=[api.models.athletes.check_yearborn]),
        ),
        migrations.AddConstraint(
            model_name='lift',
            constraint=models.UniqueConstraint(fields=('competition', 'lottery_number', 'session_number'), name='session_lottery_unique_combination'),
        ),
        migrations.AddConstraint(
            model_name='lift',
            constraint=models.UniqueConstraint(fields=('competition', 'athlete'), name='competition_athlete_unique_combination'),
        ),
    ]
