# Generated by Django 4.0.3 on 2022-03-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="competitionmodel",
            old_name="event_name",
            new_name="competition_name",
        ),
    ]
