# Generated by Django 4.0.6 on 2022-07-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_athlete_yearborn_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["-date_start", "name"]},
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="competition_name",
            new_name="name",
        ),
    ]
