# Generated by Django 4.0.6 on 2022-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_team_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="team",
            field=models.CharField(blank=True, default="IND", max_length=128),
        ),
    ]
