# Generated by Django 4.1.1 on 2022-09-21 22:36

import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_lift_weight_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Era",
            fields=[
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_start", models.DateField(blank=True, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "ordering": ["-date_start"],
            },
        ),
    ]
