# Generated by Django 4.1.1 on 2022-09-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_era"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="era",
            options={
                "get_latest_by": "-date_start",
                "ordering": ["-date_start"],
            },
        ),
    ]
