# Generated by Django 4.1.1 on 2022-09-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_era_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="era",
            options={
                "get_latest_by": ["-date_start"],
                "ordering": ["-date_start"],
            },
        ),
        migrations.AddField(
            model_name="era",
            name="category_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WGT", "Weight Categories"),
                    ("AGE", "Age Categories"),
                    ("GRD", "Grades"),
                    ("SC", "Sinclair"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="era",
            name="date_start",
            field=models.DateField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="era",
            constraint=models.UniqueConstraint(
                fields=("category_type", "date_start"),
                name="category_type_date_start_unique_combination",
            ),
        ),
    ]
