# Generated by Django 4.1.1 on 2022-09-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_era_options_era_category_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Era",
        ),
    ]
