# Generated by Django 4.0.3 on 2022-03-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_session_session_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lift",
            name="session",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.session",
            ),
            preserve_default=False,
        ),
    ]
