# Generated by Django 4.1.1 on 2022-09-22 04:59

import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_agecategory_era_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeCategoryEra",
            fields=[
                ("date_start", models.DateField(blank=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_start"],
                "get_latest_by": ["-date_start"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="agecategory",
            name="era",
        ),
        migrations.DeleteModel(
            name="Era",
        ),
    ]
