# Generated by Django 4.1.1 on 2022-09-22 22:52

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_agecategory_era"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightCategoryEra",
            fields=[
                ("date_start", models.DateField(blank=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_start"],
                "get_latest_by": ["-date_start"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="agecategory",
            name="era",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.agecategoryera",
            ),
        ),
        migrations.CreateModel(
            name="WeightCategory",
            fields=[
                (
                    "reference_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Men's"), ("W", "Women's")],
                        max_length=1,
                    ),
                ),
                ("weight", models.IntegerField(blank=True)),
                ("is_plus", models.BooleanField(blank=True, default=False)),
                (
                    "age_categories",
                    models.ManyToManyField(blank=True, to="api.agecategory"),
                ),
                (
                    "era",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.weightcategoryera",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "weigth_categories",
            },
        ),
        migrations.AddConstraint(
            model_name="weightcategory",
            constraint=models.UniqueConstraint(
                fields=("era", "sex", "weight"),
                name="era_sex_weight_unique_combination",
            ),
        ),
    ]
