# Generated by Django 4.1.1 on 2022-09-22 23:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_weightcategoryera_alter_agecategory_era_and_more"),
    ]

    operations = []
