# Generated by Django 4.1.1 on 2022-09-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20220923_1135"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agecategory",
            options={
                "ordering": ["lower_age_bound", "upper_age_bound"],
                "verbose_name_plural": "Age categories",
            },
        ),
        migrations.AlterModelOptions(
            name="agecategoryera",
            options={
                "get_latest_by": ["date_start"],
                "ordering": ["date_start"],
            },
        ),
        migrations.AlterModelOptions(
            name="weightcategory",
            options={"verbose_name_plural": "Weight categories"},
        ),
        migrations.AlterModelOptions(
            name="weightcategoryera",
            options={
                "get_latest_by": ["date_start"],
                "ordering": ["date_start"],
            },
        ),
        migrations.AlterField(
            model_name="agecategoryera",
            name="date_start",
            field=models.DateField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="weightcategoryera",
            name="date_start",
            field=models.DateField(blank=True, unique=True),
        ),
    ]
