# Generated by Django 4.1.1 on 2022-09-27 10:42

import django.db.models.deletion
import hashid_field.field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0018_alter_agecategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCompetition",
            fields=[
                (
                    "reference_id",
                    models.IntegerField(blank=True, db_index=True),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("location", models.CharField(blank=True, max_length=128)),
                ("date_start", models.DateField(blank=True)),
                ("date_end", models.DateField(blank=True)),
                (
                    "history_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        editable=False,
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical competition",
                "verbose_name_plural": "historical competitions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
