# Generated by Django 4.0.3 on 2022-04-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_lift_reference_id_alter_session_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="bodyweight",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
