# Generated by Django 4.1.2 on 2022-10-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_historicallift_historicalathlete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weightcategory",
            name="age_categories",
        ),
        migrations.RemoveField(
            model_name="weightcategory",
            name="era",
        ),
        migrations.DeleteModel(
            name="AgeCategory",
        ),
        migrations.DeleteModel(
            name="AgeCategoryEra",
        ),
        migrations.DeleteModel(
            name="WeightCategory",
        ),
        migrations.DeleteModel(
            name="WeightCategoryEra",
        ),
    ]
