# Generated by Django 4.1.1 on 2022-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_historicallift_historicalathlete"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallift",
            name="new_cnj_first",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicallift",
            name="new_cnj_second",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicallift",
            name="new_cnj_third",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicallift",
            name="new_snatch_first",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicallift",
            name="new_snatch_second",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicallift",
            name="new_snatch_third",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lift",
            name="new_cnj_first",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lift",
            name="new_cnj_second",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lift",
            name="new_cnj_third",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lift",
            name="new_snatch_first",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lift",
            name="new_snatch_second",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lift",
            name="new_snatch_third",
            field=models.IntegerField(null=True),
        ),
    ]
