# Generated by Django 4.0.3 on 2022-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_lift_bodyweight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athlete",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["-date_start", "competition_name"]},
        ),
        migrations.AlterModelOptions(
            name="lift",
            options={"ordering": ["weight_category", "lottery_number"]},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["session_datetime"]},
        ),
        migrations.AlterField(
            model_name="lift",
            name="team",
            field=models.CharField(blank=True, default="IND", max_length=20),
        ),
        migrations.AlterField(
            model_name="lift",
            name="weight_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M55", "M55"),
                    ("M61", "M61"),
                    ("M67", "M67"),
                    ("M73", "M73"),
                    ("M81", "M81"),
                    ("M89", "M89"),
                    ("M96", "M96"),
                    ("M102", "M102"),
                    ("M109", "M109"),
                    ("M102+", "M102+"),
                    ("M109+", "M109+"),
                    ("W45", "W45"),
                    ("W49", "W49"),
                    ("W55", "W55"),
                    ("W59", "W59"),
                    ("W64", "W64"),
                    ("W71", "W71"),
                    ("W76", "W76"),
                    ("W81", "W81"),
                    ("W87", "W87"),
                    ("W81+", "W81+"),
                    ("W87+", "W87+"),
                ],
                max_length=5,
            ),
        ),
    ]
