# Generated by Django 4.1.1 on 2022-10-03 04:24

from django.db import migrations


def _process_lift(status, weight):
    return {"DNA": None, "NOLIFT": -1 * weight, "LIFT": weight}.get(status)


def populate_new_lift_columns(apps, schema_editor):
    """Populate."""
    Lift = apps.get_model("api", "Lift")
    for lift in Lift.objects.all():
        lift.new_snatch_first = _process_lift(
            lift.snatch_first, lift.snatch_first_weight
        )
        lift.new_snatch_second = _process_lift(
            lift.snatch_second, lift.snatch_second_weight
        )
        lift.new_snatch_third = _process_lift(
            lift.snatch_third, lift.snatch_third_weight
        )
        lift.new_cnj_first = _process_lift(
            lift.cnj_first, lift.cnj_first_weight
        )
        lift.new_cnj_second = _process_lift(
            lift.cnj_second, lift.cnj_second_weight
        )
        lift.new_cnj_third = _process_lift(
            lift.cnj_third, lift.cnj_third_weight
        )
        lift.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_historicallift_new_cnj_first_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_new_lift_columns,
            migrations.RunPython.noop,
        )
    ]
