# Generated by Django 4.1.1 on 2022-10-03 08:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_auto_20221003_1724"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="date_ended",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="date_established",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2022, 10, 3, 21, 58, 23, 870194),
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
