# Generated by Django 4.1.1 on 2022-10-03 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_team_team_team_date_ended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="date_established",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now
            ),
        ),
    ]
