---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - args:
          - --maxkb=2000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
      - args:
          - --pytest-test-first
        id: name-tests-test
        exclude: ".*tests/factories/(.*).py"
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - args:
          - --all
        id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
  - hooks:
      - id: black
    repo: https://github.com/ambv/black
    rev: 23.9.1
  - hooks:
      - additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
          - flake8-simplify
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 6.1.0
  - hooks:
      - args:
          - -iii
          - -ll
        id: bandit
    repo: https://github.com/pycqa/bandit
    rev: 1.7.5
  - hooks:
      - additional_dependencies:
          - djangorestframework-stubs
          - django-stubs
          - django-cors-headers
          - django-allauth
          - dj_rest_auth
          - drf_spectacular
          - drf_spectacular_sidecar
          - djangorestframework-simplejwt
          - psycopg2-binary
          - psycopg2
          - django-hashid-field
          - django_extensions
          - sentry-sdk
          - django-filter
          - django-crispy-forms
          - whitenoise
          - django-debug-toolbar
          - django-auditlog
          - faker
          - factory-boy
          - pytest-factoryboy
          - django-simple-history
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - args:
          - --py3-plus
          - --py36-plus
          - --py37-plus
          - --py38-plus
          - --py39-plus
          - --py310-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
  - hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
    rev: 1.15.0
    repo: https://github.com/adamchainz/django-upgrade
  - hooks:
      - id: hadolint
    repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.2
  - hooks:
      - additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest

        files: \.[jt]sx?$
        id: eslint
        types:
          - file
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
  - hooks:
      - id: prettier
        types_or:
          [
            css,
            javascript,
            jsx,
            tsx,
            ts,
            html,
            markdown,
            scss,
            yaml,
            gitignore,
            toml,
          ]
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: 3.10.0
