# Generated by Django 4.0.3 on 2022-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_liftermodel_lifter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liftermodel",
            name="lifter_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="session_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
