# Generated by Django 4.0.3 on 2022-03-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_liftermodel_lifter_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AthleteModel",
            new_name="Athlete",
        ),
        migrations.RenameModel(
            old_name="CompetitionModel",
            new_name="Competition",
        ),
        migrations.RenameModel(
            old_name="LifterModel",
            new_name="Lift",
        ),
        migrations.RenameModel(
            old_name="SessionModel",
            new_name="Session",
        ),
        migrations.RenameField(
            model_name="lift",
            old_name="lifter_id",
            new_name="lift_id",
        ),
    ]
