# Generated by Django 4.0.3 on 2022-03-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_lift_session_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="lottery_number",
            field=models.IntegerField(blank=True),
        ),
    ]
