"""Mock Data"""

ATHLETES = (
    {  # a0
        "first_name": "Athlete",
        "last_name": "ZERO",
        "yearborn": 2000,
    },
    {  # a1
        "first_name": "Athlete",
        "last_name": "ONE",
        "yearborn": 2001,
    },
    {  # a2
        "first_name": "Athlete",
        "last_name": "TWO",
        "yearborn": 2002,
    },
    {  # a3
        "first_name": "Athlete",
        "last_name": "THREE",
        "yearborn": 2003,
    },
)


SESSIONS = (
    {  # s0
        "competition": 0,
        "session_datetime": "2022-01-01T07:00:00Z",
        "referee_first": "Referee 1",
        "referee_second": "Referee 2",
        "referee_third": "Referee 3",
        "announcer": "Announcer",
        "technical_controller": "TC",
        "marshall": "Marshall",
        "timekeeper": "TK",
        "jury": "Jury",
    },
    {  # s1
        "competition": 0,
        "session_datetime": "2022-02-01T07:00:00Z",
        "referee_first": "Referee 1",
        "referee_second": "Referee 2",
        "referee_third": "Referee 3",
        "announcer": "Announcer",
        "technical_controller": "TC",
        "marshall": "Marshall",
        "timekeeper": "TK",
        "jury": "Jury",
    },
    {  # s2
        "competition": 1,
        "session_datetime": "2022-02-02T07:00:00Z",
        "referee_first": "Referee 1",
        "referee_second": "Referee 2",
        "referee_third": "Referee 3",
        "announcer": "Announcer",
        "technical_controller": "TC",
        "marshall": "Marshall",
        "timekeeper": "TK",
        "jury": "Jury",
    },
)

# TODO: mock the lift data
LIFTS = (
    {  # l0
        "athlete": 0,
        "competition": 0,
        "session": 0,
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 0,
    },
    {  # l1
        "athlete": 1,
        "competition": 0,
        "session": 0,
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 1,
    },
    {  # l2
        "athlete": 2,
        "competition": 0,
        "session": 1,
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 0,
    },
    {  # l3
        "athlete": 3,
        "competition": 0,
        "session": 1,
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 1,
    },
    {  # l4
        "athlete": 0,
        "competition": 1,
        "session": 0,  # session 0 of comp 0
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 0,
    },
    {  # l5
        "athlete": 1,
        "competition": 1,
        "session": 0,  # session 0 of comp 0
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 1,
    },
    {  # l6
        "athlete": 2,
        "competition": 1,
        "session": 0,  # session 0 of comp 0
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 2,
    },
    {  # l7
        "athlete": 3,
        "competition": 1,
        "session": 0,  # session 0 of comp 0
        "snatch_first": "LIFT",
        "snatch_first_weight": 100,
        "snatch_second": "LIFT",
        "snatch_second_weight": 101,
        "snatch_third": "LIFT",
        "snatch_third_weight": 102,
        "cnj_first": "LIFT",
        "cnj_first_weight": 100,
        "cnj_second": "LIFT",
        "cnj_second_weight": 101,
        "cnj_third": "LIFT",
        "cnj_third_weight": 102,
        "bodyweight": 102.00,
        "weight_category": "M102+",
        "team": "TEST",
        "lottery_number": 3,
    },
)
