# Generated by Django 4.0.3 on 2022-03-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_lift_session_lift_session_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='lift_id',
            new_name='reference_id',
        ),
    ]
