# Generated by Django 4.0.3 on 2022-03-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_lift_id_lift_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="lottery_number",
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
