# Generated by Django 4.0.3 on 2022-03-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_lift_lottery_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "reference_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("session_number", models.IntegerField(unique=True)),
                ("session_datetime", models.DateTimeField(blank=True)),
                (
                    "referee_first",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "referee_second",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "referee_third",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "technical_controller",
                    models.CharField(blank=True, max_length=128),
                ),
                ("marshall", models.CharField(blank=True, max_length=255)),
                ("timekeeper", models.CharField(blank=True, max_length=255)),
                ("jury", models.CharField(blank=True, max_length=255)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.competition",
                    ),
                ),
            ],
        ),
    ]
