# Generated by Django 4.0.3 on 2022-03-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="announcer",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
