# Generated by Django 4.0.3 on 2022-03-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_session_announcer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="session_number",
        ),
    ]
