# Generated by Django 4.0.3 on 2022-03-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_lift_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lift",
            name="session_datetime",
        ),
        migrations.RemoveField(
            model_name="lift",
            name="session_number",
        ),
    ]
