# Generated by Django 4.0.3 on 2022-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_lift_lottery_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="weight_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M55", "M55"),
                    ("M61", "M61"),
                    ("M67", "M67"),
                    ("M73", "M73"),
                    ("M81", "M81"),
                    ("M89", "M89"),
                    ("M96", "M96"),
                    ("M102", "M102"),
                    ("M102+", "M102+"),
                    ("M102", "M102"),
                    ("M102+", "M102+"),
                    ("W45", "W45"),
                    ("W49", "W49"),
                    ("W55", "W55"),
                    ("W59", "W59"),
                    ("W64", "W64"),
                    ("W71", "W71"),
                    ("W76", "W76"),
                    ("W81", "W81"),
                    ("W81+", "W81+"),
                ],
                max_length=5,
            ),
        ),
    ]
