# Generated by Django 4.0.3 on 2022-03-24 00:08

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_lift_competition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="reference_id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="reference_id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
